import { DebtItem, UserFinancialProfile } from '@/types/debt';

export interface PresetScenario {
  id: string;
  name: string;
  tagline: string;
  badge: string;
  profile: UserFinancialProfile;
  debts: DebtItem[];
}

export const PRESET_SCENARIOS: PresetScenario[] = [
  {
    id: 'high_interest_cards',
    name: 'High-APR Card Overwhelm',
    tagline: 'Stuck paying massive 24%+ interest across multiple credit cards and a personal loan',
    badge: 'High Savings Potential',
    profile: {
      name: 'Alex Miller',
      currency: 'USD',
      payFrequency: 'bi-weekly',
      incomePerPeriod: 2600, // ~$5,633/mo
      monthlyNetIncome: 5633,
      livingExpenses: 3400,
      expensesBreakdown: {
        housing: 1650,
        utilities: 280,
        groceries: 650,
        transportation: 320,
        insurance: 220,
        subscriptions: 120,
        other: 160,
      },
      manualExtraMonthlySurplus: 450,
    },
    debts: [
      {
        id: 'debt-1',
        name: 'Chase Sapphire Preferred',
        category: 'credit_card',
        balance: 7850,
        apr: 28.49,
        minPayment: 215,
        dueDate: 12,
        customPriority: 1,
        notes: 'High APR travel card balance from relocation expenses',
        color: '#f43f5e',
      },
      {
        id: 'debt-2',
        name: 'Citi Double Cash',
        category: 'credit_card',
        balance: 4600,
        apr: 24.24,
        minPayment: 135,
        dueDate: 19,
        customPriority: 2,
        notes: 'General balance',
        color: '#fb923c',
      },
      {
        id: 'debt-3',
        name: 'Apple Card (Goldman Sachs)',
        category: 'credit_card',
        balance: 2400,
        apr: 21.99,
        minPayment: 75,
        dueDate: 30,
        customPriority: 3,
        notes: 'Tech upgrades',
        color: '#facc15',
      },
      {
        id: 'debt-4',
        name: 'SoFi Consolidation Loan',
        category: 'personal_loan',
        balance: 11200,
        apr: 12.5,
        minPayment: 310,
        dueDate: 5,
        customPriority: 4,
        notes: 'Consolidated old moving bills',
        color: '#38bdf8',
      },
    ],
  },
  {
    id: 'young_professional',
    name: 'Young Professional Starter',
    tagline: 'Recent graduate balancing student loans, first car purchase, and a starter card',
    badge: 'Career Starter',
    profile: {
      name: 'Taylor Reed',
      currency: 'USD',
      payFrequency: 'semi-monthly',
      incomePerPeriod: 2400, // $4,800/mo
      monthlyNetIncome: 4800,
      livingExpenses: 2850,
      expensesBreakdown: {
        housing: 1400,
        utilities: 220,
        groceries: 550,
        transportation: 260,
        insurance: 180,
        subscriptions: 90,
        other: 150,
      },
      manualExtraMonthlySurplus: 350,
    },
    debts: [
      {
        id: 'debt-yp-1',
        name: 'Discover it Cash Back',
        category: 'credit_card',
        balance: 3150,
        apr: 26.99,
        minPayment: 95,
        dueDate: 8,
        customPriority: 1,
        color: '#f43f5e',
      },
      {
        id: 'debt-yp-2',
        name: 'Honda Financial (Civic)',
        category: 'auto_loan',
        balance: 14800,
        apr: 6.49,
        minPayment: 325,
        dueDate: 16,
        customPriority: 3,
        color: '#38bdf8',
      },
      {
        id: 'debt-yp-3',
        name: 'Federal Direct Student Loan (Group A)',
        category: 'student_loan',
        balance: 18500,
        apr: 5.5,
        minPayment: 198,
        dueDate: 22,
        customPriority: 4,
        color: '#818cf8',
      },
      {
        id: 'debt-yp-4',
        name: 'Federal Direct Student Loan (Group B)',
        category: 'student_loan',
        balance: 9400,
        apr: 4.8,
        minPayment: 102,
        dueDate: 22,
        customPriority: 2,
        color: '#a78bfa',
      },
    ],
  },
  {
    id: 'family_reset',
    name: 'Family Growth & Amortization',
    tagline: 'Household managing an auto loan, home improvement loan, and emergency medical bill',
    badge: 'Household Scale',
    profile: {
      name: 'Jordan & Sam',
      currency: 'USD',
      payFrequency: 'monthly',
      incomePerPeriod: 8200,
      monthlyNetIncome: 8200,
      livingExpenses: 5400,
      expensesBreakdown: {
        housing: 2800,
        utilities: 420,
        groceries: 950,
        transportation: 450,
        insurance: 380,
        subscriptions: 140,
        other: 260,
      },
      manualExtraMonthlySurplus: 600,
    },
    debts: [
      {
        id: 'debt-fam-1',
        name: 'CareCredit (Dental Surgery)',
        category: 'medical',
        balance: 2800,
        apr: 29.99,
        minPayment: 110,
        dueDate: 7,
        customPriority: 1,
        notes: '0% promo expiring in 2 months, jumping to 29.99%',
        color: '#f43f5e',
      },
      {
        id: 'debt-fam-2',
        name: 'Home Depot Project Card',
        category: 'credit_card',
        balance: 5400,
        apr: 19.99,
        minPayment: 155,
        dueDate: 14,
        customPriority: 2,
        color: '#fb923c',
      },
      {
        id: 'debt-fam-3',
        name: 'Toyota Highlander Loan',
        category: 'auto_loan',
        balance: 21500,
        apr: 7.25,
        minPayment: 465,
        dueDate: 21,
        customPriority: 3,
        color: '#38bdf8',
      },
      {
        id: 'debt-fam-4',
        name: 'Solar Panel Green Loan',
        category: 'personal_loan',
        balance: 14200,
        apr: 5.99,
        minPayment: 185,
        dueDate: 28,
        customPriority: 4,
        color: '#34d399',
      },
    ],
  },
  {
    id: 'blank_slate',
    name: 'Custom Blank Canvas',
    tagline: 'Start fresh with your own specific debts, income, and expenses',
    badge: 'Clean Slate',
    profile: {
      name: 'My Financial Plan',
      currency: 'USD',
      payFrequency: 'monthly',
      incomePerPeriod: 5000,
      monthlyNetIncome: 5000,
      livingExpenses: 3000,
      expensesBreakdown: {
        housing: 1500,
        utilities: 300,
        groceries: 600,
        transportation: 300,
        insurance: 150,
        subscriptions: 50,
        other: 100,
      },
      manualExtraMonthlySurplus: 300,
    },
    debts: [
      {
        id: 'debt-blank-1',
        name: 'Primary Credit Card',
        category: 'credit_card',
        balance: 5000,
        apr: 22.9,
        minPayment: 150,
        dueDate: 15,
        customPriority: 1,
        color: '#f43f5e',
      },
    ],
  },
];

export const DEBT_CATEGORY_LABELS: Record<
  string,
  { label: string; icon: string; defaultColor: string; typicalApr: number }
> = {
  credit_card: {
    label: 'Credit Card (Revolving)',
    icon: 'CreditCard',
    defaultColor: '#f43f5e',
    typicalApr: 24.99,
  },
  personal_loan: {
    label: 'Personal / Consolidation Loan',
    icon: 'Landmark',
    defaultColor: '#fb923c',
    typicalApr: 11.5,
  },
  auto_loan: {
    label: 'Auto Loan',
    icon: 'Car',
    defaultColor: '#38bdf8',
    typicalApr: 6.99,
  },
  student_loan: {
    label: 'Student Loan',
    icon: 'GraduationCap',
    defaultColor: '#818cf8',
    typicalApr: 5.8,
  },
  mortgage: {
    label: 'Mortgage / Real Estate',
    icon: 'Home',
    defaultColor: '#34d399',
    typicalApr: 6.75,
  },
  medical: {
    label: 'Medical Debt',
    icon: 'HeartPulse',
    defaultColor: '#f472b6',
    typicalApr: 18.0,
  },
  other: {
    label: 'Other Liability',
    icon: 'Coins',
    defaultColor: '#94a3b8',
    typicalApr: 10.0,
  },
};
